// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// CmsCrawlProxy is the golang structure for table cms_crawl_proxy.
type CmsCrawlProxy struct {
	Id           int         `json:"id"           ` // 主键ID
	TargetDomain string      `json:"targetDomain" ` // 目标网站顶级域名
	ProxyUrl     string      `json:"proxyUrl"     ` // 代理地址
	ProxyStatus  int         `json:"proxyStatus"  ` // 代理状态. 0-停用,1-使用中
	CreateUser   int         `json:"createUser"   ` // 添加人
	CreateTime   *gtime.Time `json:"createTime"   ` // 添加时间
	UpdateUser   int         `json:"updateUser"   ` // 更新人
	UpdateTime   *gtime.Time `json:"updateTime"   ` // 更新时间
}
