// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// CmsCrawlLiveConfig is the golang structure for table cms_crawl_live_config.
type CmsCrawlLiveConfig struct {
	Id            int         `json:"id"            ` // 主键ID
	GroupName     string      `json:"groupName"     ` // 直播流分组名.(同一个分组被分配到1台机器)
	ProgramName   string      `json:"programName"   ` // 节目名称.(用于展示，提示等)
	ProgramSource string      `json:"programSource" ` // 节目来源.(如网站域名)
	LiveType      int         `json:"liveType"      ` // 直播源类型. 1-M3U8类型;2-持续流类型
	LiveUrl       string      `json:"liveUrl"       ` // 直播流地址
	ChannelIcon   string      `json:"channelIcon"   ` //
	ErrorMsg      string      `json:"errorMsg"      ` // 错误信息
	Status        int         `json:"status"        ` // 状态：1在用 2停用
	Sort          int         `json:"sort"          ` // 排序
	Note          string      `json:"note"          ` // 备注
	Mark          int         `json:"mark"          ` // 有效标识(1正常 0删除)
	CreateUser    int         `json:"createUser"    ` // 添加人
	CreateTime    *gtime.Time `json:"createTime"    ` // 添加时间
	UpdateUser    int         `json:"updateUser"    ` // 更新人
	UpdateTime    *gtime.Time `json:"updateTime"    ` // 更新时间
}
