// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// CmsUploadCluster is the golang structure for table cms_upload_cluster.
type CmsUploadCluster struct {
	Id               int         `json:"id"               ` // 集群ID
	ClusterNo        string      `json:"clusterNo"        ` // 集群编码.(仅用于助记. eg: 集群A,集群B,...)
	ClusterIps       string      `json:"clusterIps"       ` // 集群IP列表，英文逗号隔开(仅用于助记)
	ClusterDu        int         `json:"clusterDu"        ` // 集群已经使用容量,单位为G(前端自行转化为T,通过定时任务来自动刷新)
	ClusterDf        int         `json:"clusterDf"        ` // 集群剩余容量,单位为G(前端自行转化为T,通过定时任务来自动刷新),可用该值进行告警
	ClusterAvailable int         `json:"clusterAvailable" ` // 是否可用. true-可用
	ClusterNote      string      `json:"clusterNote"      ` // 备注
	CreateUser       int         `json:"createUser"       ` // 添加人
	CreateTime       *gtime.Time `json:"createTime"       ` // 添加时间
	UpdateUser       int         `json:"updateUser"       ` // 更新人
	UpdateTime       *gtime.Time `json:"updateTime"       ` // 更新时间
}
