// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// CmsCrawlDict is the golang structure for table cms_crawl_dict.
type CmsCrawlDict struct {
	Id         int64  `json:"id"         ` // ID
	Namespace  string `json:"namespace"  ` // 命名空间
	DictKey    string `json:"dictKey"    ` // 键名
	DictValue  string `json:"dictValue"  ` // 键值
	DictSort   int    `json:"dictSort"   ` //
	DictStatus int    `json:"dictStatus" ` // 状态. 0-停用；1-启用
	DictDesc   string `json:"dictDesc"   ` // 描述
}
