// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// CmsCrawlReplayProgramTask is the golang structure for table cms_crawl_replay_program_task.
type CmsCrawlReplayProgramTask struct {
	Id               int         `json:"id"               ` // 主键ID
	HostIp           string      `json:"hostIp"           ` //
	ManifestId       int         `json:"manifestId"       ` // 队列ID
	ConfigId         int         `json:"configId"         ` // 配置单ID
	ProgramNo        string      `json:"programNo"        ` // 节目编号
	ProgramName      string      `json:"programName"      ` // 节目名称
	ProgramStartTime *gtime.Time `json:"programStartTime" ` // 节目开始时间
	ProgramEndTime   *gtime.Time `json:"programEndTime"   ` // 节目结束时间
	ProgramFilePath  string      `json:"programFilePath"  ` //
	ProgramServerUrl string      `json:"programServerUrl" ` //
	ProgramPlayUrl   string      `json:"programPlayUrl"   ` //
	CrawlStatus      int         `json:"crawlStatus"      ` // 抓取状态.0-创建任务;1-录制中;2-录制失败;3-录制完成;
	ErrorMsg         string      `json:"errorMsg"         ` // 错误信息
	CreateUser       int         `json:"createUser"       ` // 添加人
	CreateTime       *gtime.Time `json:"createTime"       ` // 添加时间
	UpdateUser       int         `json:"updateUser"       ` // 更新人
	UpdateTime       *gtime.Time `json:"updateTime"       ` // 更新时间
}
