// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// CmsCrawlVodTv is the golang structure for table cms_crawl_vod_tv.
type CmsCrawlVodTv struct {
	Id            int         `json:"id"            ` // 主键ID
	VodConfigId   int         `json:"vodConfigId"   ` // 配置表主键ID
	VodMd5        string      `json:"vodMd5"        ` // 电视剧md5。防重复抓取
	CrawlStatus   int         `json:"crawlStatus"   ` // 抓取状态.0-创建任务;1-自动补全视频信息中;2-补充视频信息失败;3-补充视频信息成功;4-补充TV ID信息中;5-补充TV ID信息失败;6-补充TV ID信息成功
	VideoCountry  string      `json:"videoCountry"  ` // 国家
	VideoYear     string      `json:"videoYear"     ` // 年份
	VideoNo       string      `json:"videoNo"       ` // 栏目编号
	VideoName     string      `json:"videoName"     ` // 视频名称
	VideoDirector string      `json:"videoDirector" ` // 视频导演
	VideoActor    string      `json:"videoActor"    ` // 视频演员
	VideoIcon     string      `json:"videoIcon"     ` // 栏目图标
	VideoDesc     string      `json:"videoDesc"     ` // 栏目描述
	SeedUrl       string      `json:"seedUrl"       ` // 种子URL
	SeedParams    string      `json:"seedParams"    ` // 种子URL携带的参数。保存Json串
	ErrorCnt      int         `json:"errorCnt"      ` // 失败次数
	ErrorMsg      string      `json:"errorMsg"      ` // 错误信息
	VideoLanguage string      `json:"videoLanguage" ` // 语言
	VideoQuality  string      `json:"videoQuality"  ` // 清晰度
	VideoTag      string      `json:"videoTag"      ` //
	VideoCollId   int64       `json:"videoCollId"   ` // 剧集ID
	CreateUser    int         `json:"createUser"    ` // 添加人
	CreateTime    *gtime.Time `json:"createTime"    ` // 添加时间
	UpdateUser    int         `json:"updateUser"    ` // 更新人
	UpdateTime    *gtime.Time `json:"updateTime"    ` // 更新时间
}
