// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// CmsCrawlReplayProgramTask is the golang structure of table cms_crawl_replay_program_task for DAO operations like Where/Data.
type CmsCrawlReplayProgramTask struct {
	g.Meta           `orm:"table:cms_crawl_replay_program_task, do:true"`
	Id               interface{} // 主键ID
	HostIp           interface{} //
	ManifestId       interface{} // 队列ID
	ConfigId         interface{} // 配置单ID
	ProgramNo        interface{} // 节目编号
	ProgramName      interface{} // 节目名称
	ProgramStartTime *gtime.Time // 节目开始时间
	ProgramEndTime   *gtime.Time // 节目结束时间
	ProgramFilePath  interface{} //
	ProgramServerUrl interface{} //
	ProgramPlayUrl   interface{} //
	CrawlStatus      interface{} // 抓取状态.0-创建任务;1-录制中;2-录制失败;3-录制完成;
	ErrorMsg         interface{} // 错误信息
	CreateUser       interface{} // 添加人
	CreateTime       *gtime.Time // 添加时间
	UpdateUser       interface{} // 更新人
	UpdateTime       *gtime.Time // 更新时间
}
