// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// CmsCrawlReplayManifestTask is the golang structure of table cms_crawl_replay_manifest_task for DAO operations like Where/Data.
type CmsCrawlReplayManifestTask struct {
	g.Meta         `orm:"table:cms_crawl_replay_manifest_task, do:true"`
	Id             interface{} // 主键ID
	ReplayConfigId interface{} // 任务ID
	ReplayDay      interface{} // 节目日
	CrawlStatus    interface{} // 抓取状态.0-创建任务;1-抓取中;2-抓取失败;3-抓取完成;
	ErrorMsg       interface{} // 错误信息
	CreateUser     interface{} // 添加人
	CreateTime     *gtime.Time // 添加时间
	UpdateUser     interface{} // 更新人
	UpdateTime     *gtime.Time // 更新时间
	Type           interface{} // 节目单生成方式 0 按爬虫地址 1 自动生成
}
