// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// CmsCrawlReplayConfig is the golang structure of table cms_crawl_replay_config for DAO operations like Where/Data.
type CmsCrawlReplayConfig struct {
	g.Meta        `orm:"table:cms_crawl_replay_config, do:true"`
	Id            interface{} // 主键ID
	ChannelNo     interface{} // 频道编号
	ChannelName   interface{} // 频道名称
	ChannelNameEn interface{} //
	ChannelIcon   interface{} //
	Type          interface{} // 节目单生成方式 0 按爬虫地址 1 自动生成
	SeedUrl       interface{} // 种子URL
	SeedParams    interface{} // 种子URL携带的参数。保存Json串
	Host          interface{} // 配置录制的机器
	Domain        interface{} //
	PlayUrl       interface{} // 播放地址(流)
	ErrorMsg      interface{} // 错误信息
	CreateUser    interface{} // 添加人
	CreateTime    *gtime.Time // 添加时间
	UpdateUser    interface{} // 更新人
	UpdateTime    *gtime.Time // 更新时间
	Status        interface{} // 状态：1在用 2停用
	Sort          interface{} // 排序
	Note          interface{} // 备注
	Mark          interface{} // 有效标识(1正常 0删除)
}
