// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// CmsCrawlVodConfig is the golang structure of table cms_crawl_vod_config for DAO operations like Where/Data.
type CmsCrawlVodConfig struct {
	g.Meta        `orm:"table:cms_crawl_vod_config, do:true"`
	Id            interface{} // 主键ID
	HostType      interface{} // 传递给crawlQueue的hostType字段。2-nivod网；3-BananTV
	VodType       interface{} // 点播类型.0-电影；1-剧集（标志给展示逻辑，爬虫统一按剧集逻辑走）
	DomainKeyPart interface{} // 域名关键部分.用于配置策略
	ProgramNo     interface{} // 栏目编号
	ProgramName   interface{} // 栏目名称
	ProgramIcon   interface{} // 栏目图标
	CategoryNo    interface{} // 分类编号
	CategoryName  interface{} // 分类名称
	SeedUrl       interface{} // 种子URL
	SeedParams    interface{} // 种子URL携带的参数。保存Json串
	SeedStatus    interface{} // 状态：1在用 2停用
	PageSize      interface{} // 翻页次数
	SeedDesc      interface{} // 描述
	ErrorMsg      interface{} // 错误信息
	CreateUser    interface{} // 添加人
	CreateTime    *gtime.Time // 添加时间
	UpdateUser    interface{} // 更新人
	UpdateTime    *gtime.Time // 更新时间
}
