// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// CmsUploadCluster is the golang structure of table cms_upload_cluster for DAO operations like Where/Data.
type CmsUploadCluster struct {
	g.Meta           `orm:"table:cms_upload_cluster, do:true"`
	Id               interface{} // 集群ID
	ClusterNo        interface{} // 集群编码.(仅用于助记. eg: 集群A,集群B,...)
	ClusterIps       interface{} // 集群IP列表，英文逗号隔开(仅用于助记)
	ClusterDu        interface{} // 集群已经使用容量,单位为G(前端自行转化为T,通过定时任务来自动刷新)
	ClusterDf        interface{} // 集群剩余容量,单位为G(前端自行转化为T,通过定时任务来自动刷新),可用该值进行告警
	ClusterAvailable interface{} // 是否可用. true-可用
	ClusterNote      interface{} // 备注
	CreateUser       interface{} // 添加人
	CreateTime       *gtime.Time // 添加时间
	UpdateUser       interface{} // 更新人
	UpdateTime       *gtime.Time // 更新时间
}
