// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// CmsCrawlLiveConfig is the golang structure of table cms_crawl_live_config for DAO operations like Where/Data.
type CmsCrawlLiveConfig struct {
	g.Meta        `orm:"table:cms_crawl_live_config, do:true"`
	Id            interface{} // 主键ID
	GroupName     interface{} // 直播流分组名.(同一个分组被分配到1台机器)
	ProgramName   interface{} // 节目名称.(用于展示，提示等)
	ProgramSource interface{} // 节目来源.(如网站域名)
	LiveType      interface{} // 直播源类型. 1-M3U8类型;2-持续流类型
	LiveUrl       interface{} // 直播流地址
	ChannelIcon   interface{} //
	ErrorMsg      interface{} // 错误信息
	Status        interface{} // 状态：1在用 2停用
	Sort          interface{} // 排序
	Note          interface{} // 备注
	Mark          interface{} // 有效标识(1正常 0删除)
	CreateUser    interface{} // 添加人
	CreateTime    *gtime.Time // 添加时间
	UpdateUser    interface{} // 更新人
	UpdateTime    *gtime.Time // 更新时间
}
