// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// CmsCrawlVodTv is the golang structure of table cms_crawl_vod_tv for DAO operations like Where/Data.
type CmsCrawlVodTv struct {
	g.Meta        `orm:"table:cms_crawl_vod_tv, do:true"`
	Id            interface{} // 主键ID
	VodConfigId   interface{} // 配置表主键ID
	VodMd5        interface{} // 电视剧md5。防重复抓取
	CrawlStatus   interface{} // 抓取状态.0-创建任务;1-自动补全视频信息中;2-补充视频信息失败;3-补充视频信息成功;4-补充TV ID信息中;5-补充TV ID信息失败;6-补充TV ID信息成功
	VideoCountry  interface{} // 国家
	VideoYear     interface{} // 年份
	VideoNo       interface{} // 栏目编号
	VideoName     interface{} // 视频名称
	VideoDirector interface{} // 视频导演
	VideoActor    interface{} // 视频演员
	VideoIcon     interface{} // 栏目图标
	VideoDesc     interface{} // 栏目描述
	SeedUrl       interface{} // 种子URL
	SeedParams    interface{} // 种子URL携带的参数。保存Json串
	ErrorCnt      interface{} // 失败次数
	ErrorMsg      interface{} // 错误信息
	VideoLanguage interface{} // 语言
	VideoQuality  interface{} // 清晰度
	VideoTag      interface{} //
	VideoCollId   interface{} // 剧集ID
	CreateUser    interface{} // 添加人
	CreateTime    *gtime.Time // 添加时间
	UpdateUser    interface{} // 更新人
	UpdateTime    *gtime.Time // 更新时间
}
