// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// CmsCrawlVodConfigTaskDao is the data access object for table cms_crawl_vod_config_task.
type CmsCrawlVodConfigTaskDao struct {
	table   string                       // table is the underlying table name of the DAO.
	group   string                       // group is the database configuration group name of current DAO.
	columns CmsCrawlVodConfigTaskColumns // columns contains all the column names of Table for convenient usage.
}

// CmsCrawlVodConfigTaskColumns defines and stores column names for table cms_crawl_vod_config_task.
type CmsCrawlVodConfigTaskColumns struct {
	Id          string // 主键ID
	VodConfigId string // vod_config表ID
	TaskStatus  string // 任务状态. 0-初始化; 1-进行中; 2-任务失败; 3-任务结束
	CreateTime  string // 添加时间
	UpdateTime  string // 更新时间
}

// cmsCrawlVodConfigTaskColumns holds the columns for table cms_crawl_vod_config_task.
var cmsCrawlVodConfigTaskColumns = CmsCrawlVodConfigTaskColumns{
	Id:          "id",
	VodConfigId: "vod_config_id",
	TaskStatus:  "task_status",
	CreateTime:  "create_time",
	UpdateTime:  "update_time",
}

// NewCmsCrawlVodConfigTaskDao creates and returns a new DAO object for table data access.
func NewCmsCrawlVodConfigTaskDao() *CmsCrawlVodConfigTaskDao {
	return &CmsCrawlVodConfigTaskDao{
		group:   "default",
		table:   "cms_crawl_vod_config_task",
		columns: cmsCrawlVodConfigTaskColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *CmsCrawlVodConfigTaskDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *CmsCrawlVodConfigTaskDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *CmsCrawlVodConfigTaskDao) Columns() CmsCrawlVodConfigTaskColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *CmsCrawlVodConfigTaskDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *CmsCrawlVodConfigTaskDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *CmsCrawlVodConfigTaskDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
