// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// CmsCrawlLiveConfigDao is the data access object for table cms_crawl_live_config.
type CmsCrawlLiveConfigDao struct {
	table   string                    // table is the underlying table name of the DAO.
	group   string                    // group is the database configuration group name of current DAO.
	columns CmsCrawlLiveConfigColumns // columns contains all the column names of Table for convenient usage.
}

// CmsCrawlLiveConfigColumns defines and stores column names for table cms_crawl_live_config.
type CmsCrawlLiveConfigColumns struct {
	Id            string // 主键ID
	GroupName     string // 直播流分组名.(同一个分组被分配到1台机器)
	ProgramName   string // 节目名称.(用于展示，提示等)
	ProgramSource string // 节目来源.(如网站域名)
	LiveType      string // 直播源类型. 1-M3U8类型;2-持续流类型
	LiveUrl       string // 直播流地址
	ChannelIcon   string //
	ErrorMsg      string // 错误信息
	Status        string // 状态：1在用 2停用
	Sort          string // 排序
	Note          string // 备注
	Mark          string // 有效标识(1正常 0删除)
	CreateUser    string // 添加人
	CreateTime    string // 添加时间
	UpdateUser    string // 更新人
	UpdateTime    string // 更新时间
}

// cmsCrawlLiveConfigColumns holds the columns for table cms_crawl_live_config.
var cmsCrawlLiveConfigColumns = CmsCrawlLiveConfigColumns{
	Id:            "id",
	GroupName:     "group_name",
	ProgramName:   "program_name",
	ProgramSource: "program_source",
	LiveType:      "live_type",
	LiveUrl:       "live_url",
	ChannelIcon:   "channel_icon",
	ErrorMsg:      "error_msg",
	Status:        "status",
	Sort:          "sort",
	Note:          "note",
	Mark:          "mark",
	CreateUser:    "create_user",
	CreateTime:    "create_time",
	UpdateUser:    "update_user",
	UpdateTime:    "update_time",
}

// NewCmsCrawlLiveConfigDao creates and returns a new DAO object for table data access.
func NewCmsCrawlLiveConfigDao() *CmsCrawlLiveConfigDao {
	return &CmsCrawlLiveConfigDao{
		group:   "default",
		table:   "cms_crawl_live_config",
		columns: cmsCrawlLiveConfigColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *CmsCrawlLiveConfigDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *CmsCrawlLiveConfigDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *CmsCrawlLiveConfigDao) Columns() CmsCrawlLiveConfigColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *CmsCrawlLiveConfigDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *CmsCrawlLiveConfigDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *CmsCrawlLiveConfigDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
