# HTTP Server.
server:
  context-path: /go-to-crawl-frame
  address: :8199
  serverRoot: public
  serverAgent: go-to-crawl-frame
  logPath: D:\app\crawl\logs\server
  nameToUriType: 2
  routeOverWrite: true
  devMode: true
  openAllTask: true

dfs:
  rootPath: D:\app\crawl\video #本地调试临时指定

crawl:
  hostIp: localhost
  debug:
    disableDB: false # 不配置默认false，表示要做某些数据库操作。本地调试某些场景需要关闭一下数据库操作
    notDownloadAll: true # 不配置默认false，表示下载所有TS片段。本地调试某些场景只需要下载部分TS加快调试速度
  #本机最大同时转码数量
  maxTrans: 5
  browser:
    browserType: chrome
    userDataDir: D:\ApplicationsPro\BrowserDriver\userData # 缓存的用户信息，用于让selenium记录用户登录状态
    proxyPath: D:\ApplicationsPro\browsermob-proxy\bin\browsermob-proxy.bat
    headless: false # 无头模式（linux等无界面渲染模式需设置为true）
    browserInfoList:
      - driverType: chrome
        driverPath: D:\ApplicationsPro\BrowserDriver\chromedriver.exe #  http://chromedriver.storage.googleapis.com/index.html 驱动下载地址 需要对应浏览器版本
        executorPath: C:\Users\Administrator\AppData\Local\MyChrome\Chrome\Application\chrone.exe
      - driverType: firefox
        driverPath: D:\ApplicationsPro\BrowserDriver\geckodriver.exe # 无需对应版本https://github.com/mozilla/geckodriver/releases/
        executorPath: D:\Applications\Mozilla Firefox\firefox.exe
        profilePath: D:\ApplicationsPro\BrowserDriver\firefoxProfile
      - driverType: edge
        driverPath: D:\ApplicationsPro\BrowserDriver\msedgedriver.exe
        executorPath: C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe

replay:
  #是录制成功后是否需要post到流媒体
  need_post: true
  #录制文件保留天数
  day: 7
  #配置当前回看机器nginx监听目录域名
  play_domain: 127.0.0.1:9999
  #回看发布URL
  callback_url: http://127.0.0.1:9011/api/noticereplay

logger:
  path: D:\app\crawl\logs\output
  level: all
  stdout: true

viewer:
  path: template
  defaultFile: index.html
  Delimiters: [ "{{", "}}" ]

# mysql:账号:密码@tcp(地址:端⼝)/数据库名称
database:
  default:
    link: mysql:{username}:{pwd}@tcp({ip}:{port})/go-to-crawl
    debug: true
  logger:
    Path: D:\app\crawl\logs\sql
    Level: all
    Stdout: true

build:
  name: test
  arch: amd64 # 386,amd64,arm
  system: linux # linux,darwin,windows
  mod: none
  cgo: 0
  pack: public,template
  version: v1.0.0
  output: D:\app\crawl\bin
  extra: 暂无