// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/JervisPG/go-to-crawl-frame/db/mysql/dao/internal"
)

// internalCmsCrawlLiveConfigDao is internal type for wrapping internal DAO implements.
type internalCmsCrawlLiveConfigDao = *internal.CmsCrawlLiveConfigDao

// cmsCrawlLiveConfigDao is the data access object for table cms_crawl_live_config.
// You can define custom methods on it to extend its functionality as you wish.
type cmsCrawlLiveConfigDao struct {
	internalCmsCrawlLiveConfigDao
}

var (
	// CmsCrawlLiveConfig is globally public accessible object for table cms_crawl_live_config operations.
	CmsCrawlLiveConfig = cmsCrawlLiveConfigDao{
		internal.NewCmsCrawlLiveConfigDao(),
	}
)

// Fill with you ideas below.
