// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/JervisPG/go-to-crawl-frame/db/mysql/dao/internal"
)

// internalCmsCrawlReplayProgramTaskDao is internal type for wrapping internal DAO implements.
type internalCmsCrawlReplayProgramTaskDao = *internal.CmsCrawlReplayProgramTaskDao

// cmsCrawlReplayProgramTaskDao is the data access object for table cms_crawl_replay_program_task.
// You can define custom methods on it to extend its functionality as you wish.
type cmsCrawlReplayProgramTaskDao struct {
	internalCmsCrawlReplayProgramTaskDao
}

var (
	// CmsCrawlReplayProgramTask is globally public accessible object for table cms_crawl_replay_program_task operations.
	CmsCrawlReplayProgramTask = cmsCrawlReplayProgramTaskDao{
		internal.NewCmsCrawlReplayProgramTaskDao(),
	}
)

// Fill with you ideas below.
