// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-to-crawl-frame/db/mysql/dao/internal"
)

// internalCmsCrawlReplayManifestTaskDao is internal type for wrapping internal DAO implements.
type internalCmsCrawlReplayManifestTaskDao = *internal.CmsCrawlReplayManifestTaskDao

// cmsCrawlReplayManifestTaskDao is the data access object for table cms_crawl_replay_manifest_task.
// You can define custom methods on it to extend its functionality as you wish.
type cmsCrawlReplayManifestTaskDao struct {
	internalCmsCrawlReplayManifestTaskDao
}

var (
	// CmsCrawlReplayManifestTask is globally public accessible object for table cms_crawl_replay_manifest_task operations.
	CmsCrawlReplayManifestTask = cmsCrawlReplayManifestTaskDao{
		internal.NewCmsCrawlReplayManifestTaskDao(),
	}
)

// Fill with you ideas below.
