// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/JervisPG/go-to-crawl-frame/db/mysql/dao/internal"
)

// internalCmsCrawlVodTvDao is internal type for wrapping internal DAO implements.
type internalCmsCrawlVodTvDao = *internal.CmsCrawlVodTvDao

// cmsCrawlVodTvDao is the data access object for table cms_crawl_vod_tv.
// You can define custom methods on it to extend its functionality as you wish.
type cmsCrawlVodTvDao struct {
	internalCmsCrawlVodTvDao
}

var (
	// CmsCrawlVodTv is globally public accessible object for table cms_crawl_vod_tv operations.
	CmsCrawlVodTv = cmsCrawlVodTvDao{
		internal.NewCmsCrawlVodTvDao(),
	}
)

// Fill with you ideas below.
