// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/JervisPG/go-to-crawl-frame/db/mysql/dao/internal"
)

// internalCmsUploadClusterDao is internal type for wrapping internal DAO implements.
type internalCmsUploadClusterDao = *internal.CmsUploadClusterDao

// cmsUploadClusterDao is the data access object for table cms_upload_cluster.
// You can define custom methods on it to extend its functionality as you wish.
type cmsUploadClusterDao struct {
	internalCmsUploadClusterDao
}

var (
	// CmsUploadCluster is globally public accessible object for table cms_upload_cluster operations.
	CmsUploadCluster = cmsUploadClusterDao{
		internal.NewCmsUploadClusterDao(),
	}
)

// Fill with you ideas below.
